[Task] Adding the HTML structure for home page1
cmvn-nghianguyen/FE-Internship-2023_Nghia-Nguyen-D_FE-Exercise pull request #4
Opened 2023-08-04 08:38 UTC by cmvn-nghianguyen

### Description
-  Adding the HTML structure to the home page of the figma link
### Checklist
- [x] App run correctly
- [x] The code has been tested in the local environment.
- [x] No convention errors

2023-08-05 18:25 UTC, st-duynguyen commented on 1.html
> +  <title>Home 1</title>
Đặt title hoàn chỉnh, ghi rõ nội dung của page vì sẽ ảnh hưởng đến SEO

2023-08-05 18:26 UTC, st-duynguyen commented on 1.html
> +      <img src="" alt="logo Eshop">
Tạo 1 folder assets/image download hết tất các image có sử dụng về để sử dụng cho các thẻ img

2023-08-05 18:27 UTC, st-duynguyen commented on 1.html
> +      <h2>E-shop</h2>
Trong 1 page thì chỉ có 1 thẻ h1 và nên sử dụng nó cho logo (liên quan đến SEO)

2023-08-05 18:29 UTC, st-duynguyen commented on 1.html
> +      <h2>E-shop</h2>
Thẻ h1 sẽ bọc lun cả image và title. Ex:
```
<h1 class="header-logo">
              <a href="#" class="logo-link shop-name">
                <img class="logo" src="asset\images\logo_black.svg" alt="E-shop" />
                E-Shop
              </a>
            </h1>

2023-08-05 18:30 UTC, st-duynguyen commented on 1.html
> +      <ul class="navbar-menu">
Nên đặt tên ul để nhìn biết là đang list. Ex: `navbar-menu-list` or `navbar-list`

2023-08-05 18:31 UTC, st-duynguyen commented on 1.html
> +      <ul>
Check lại 1 lượt, đặt tên class cho tất cả các thẻ bao gồm cả thẻ ul, li, a, p....

2023-08-05 18:32 UTC, st-duynguyen commented on 1.html
> +        <li><i class='bx bx-search'></i></li>
Bọc thẻ a cho những icon hay title cần link sang trang khác. Ex:
```
<li class="list-item">
    <a class="logo-link" href="#">
      <img src="asset\images\search.svg" alt="search_icon">
    </a>
  </li>

2023-08-05 18:33 UTC, st-duynguyen commented on 1.html
> +  <section>
Check lại đặt tên class cho tất các section theo format section-nội dung chính của section. Ex: `section-top-banner`

2023-08-05 18:54 UTC, st-duynguyen commented on 1.html
> +    <h1 class="title">Sale of the <br> summer <br> collection</h1>
Thẻ h1 đã đặt trên logo rồi thì đổi thẻ ni thành h khác

2023-08-05 18:55 UTC, st-duynguyen commented on 1.html
> +    <div class="button-shop">
đặt thẻ a cho những button hay text cần link sang trang khác. Ex: 
```
<a class="banner-link" href="#">
              <span class="arrow-icon">
                <i class="fas fa-arrow-right"></i>
              </span>
              SHOP NOW
            </a>

2023-08-05 18:56 UTC, st-duynguyen commented on 1.html
> +    <ul class="content-provide">
Check lại 1 lượt tất cả các class của ul vs li theo comment của a ở trên

2023-08-05 18:57 UTC, st-duynguyen commented on 1.html
> +        <div class="content-item">
trong div lớn chia thành 2 mục nhỏ: image vs 1 div content chứa title vs content

2023-08-05 19:00 UTC, st-duynguyen commented on 1.html
> +          <i class='bx bxs-car'></i>
- K phải tất cả các chỗ đều dùng tag i, chỉ dùng thẻ i cho những icon thôi, còn lại phải dùng img.

2023-08-05 19:00 UTC, st-duynguyen commented on 1.html
> +        <div class="shipping-service">
trong div lớn chia thành 2 mục nhỏ: image vs 1 div content chứa title vs content

2023-08-05 19:02 UTC, st-duynguyen requested changes
@cmvn-nghianguyen Bài làm còn sơ sài.
- E phải viết html, đặt tên class hoàn chỉnh cho tất cả những thẻ có trong bài
- Download image về để bỏ vào thư mục, viết hoàn chỉnh các thẻ image

2023-08-06 13:25 UTC, st-duynguyen commented on 1.html
> +  <section class="container-1">
nên đặt tên section theo format mà a đã comment ở trước. section-nội dung section. Ko nên đặt tên class đại như trên

2023-08-06 13:30 UTC, st-duynguyen commented on 1.html
> +          <h2 class="slide-content">New arrivalsare now in!</h2>
Vì sao lại đặt thằng này tới tận h2 vậy e

2023-08-06 13:30 UTC, st-duynguyen commented on 1.html
> +          <h2 class="slide-content">Basic t-shirts <br> $29,99</h2>
Check tương tự cmt như trên

2023-08-06 13:31 UTC, st-duynguyen commented on 1.html
> +          <h2 class="slide-content">Sale this <br> summer</h2>
Check tương tự cmt như trên

2023-08-06 13:34 UTC, st-duynguyen commented on 1.html
> +    <input type="text" id="email" name="username" placeholder="Enter your email">
phải có 1 thẻ form bọc cho thằng input vs button submit

2023-08-06 13:34 UTC, st-duynguyen commented on 1.html
> +  <section>
thiếu class cho section này

2023-08-06 13:34 UTC, st-duynguyen commented on 1.html
> +  <section>
đặt tên thiếu class cho section

2023-08-06 13:35 UTC, st-duynguyen commented on 1.html
> +  <section>
đặt tên thiếu class cho section

2023-08-06 13:36 UTC, st-duynguyen commented on 1.html
> +      <li class="service">
sửa class li lại thành `service-item`

2023-08-06 13:37 UTC, st-duynguyen commented on 1.html
> +        <h2 class="service-title">Free Shipping</h2>
Phải có 1 div bọc ở ngoài title vs content. Chỗ này sao lại để là thẻ h2 cùng với title bự bên ngoài ul??

2023-08-06 13:39 UTC, st-duynguyen commented on 1.html
> +      <li class="card">
Check lại 1 lượt, những thẻ li nên thêm -item phía sao để dễ clear

2023-08-06 13:44 UTC, st-duynguyen commented on 1.html
> +      <h2 class="shopping-title">Shopping online</h2>
Check lại, thằng này nên là h nhỏ hơn thằng logo, tức nhỏ hơn h2

2023-08-07 09:55 UTC, st-duynguyen commented on 1.html
> +            <p class="content-description">On purchases over $199</p>
Thẻ p ko bọc trong thẻ h3, sửa lại cho tất cả tương tự ở dưới

2023-08-07 09:56 UTC, st-duynguyen commented on 1.html
> +        <div class="content-container">
ko nên dùng tên container cho những thằng class nhỏ ni e. Chỉ nên đặt 1 class container chung cho div con của thằng section bự thôi

2023-08-07 09:59 UTC, st-duynguyen commented on 1.html
> +            <h2 class="slide-content">New arrivalsare now in!</h2>
thằng này nên để h4

2023-08-07 10:00 UTC, st-duynguyen commented on 1.html
> +            <h2 class="slide-content">Basic t-shirts <br> $29,99</h2>
thằng này nên để h4

2023-08-07 10:00 UTC, st-duynguyen commented on 1.html
> +            <a class="slide-button">SHOW COLLECTION</a>
Thằng này nên để button chứ k phải thẻ a

2023-08-07 10:01 UTC, st-duynguyen commented on 1.html
> +            <h2 class="slide-content">Sale this <br> summer</h2>
thẻ h và button check tương tự comment trên

2023-08-07 10:02 UTC, st-duynguyen commented on 1.html
> +      <a class="title-card-button">SHOW MORE</a>
E check lại kĩ 1 lượt chỗ nào nên dùng buttton, chỗ nào nên dùng thẻ a

2023-08-07 10:02 UTC, st-duynguyen commented on 1.html
> +      <h2 class="title-card-content">Selected just for you</h2>
Tất cả những title bự tương tự nên set h3

2023-08-07 10:05 UTC, st-duynguyen commented on 1.html
> +          <h2 class="service-title">Free Shipping</h2>
Nên bọc 1 div chưa title và content. Example:

![Screen Shot 2023-08-07 at 5 05 04 PM](https://github.com/cmvn-nghianguyen/FE-Internship-2023_Nghia-Nguyen-D_FE-Exercise/assets/62866904/7c31ea45-06ae-4ae2-b7e3-2e2731fbd8ae)

2023-08-07 23:33 UTC, st-ngabui approved these changes

2023-08-07 23:33 UTC, merged