[Task] Adding the CSS file for figma E-shop
cmvn-nghianguyen/FE-Internship-2023_Nghia-Nguyen-D_FE-Exercise pull request #6
Opened 2023-08-08 10:08 UTC by cmvn-nghianguyen

### Description
-  Adding the CSS style to the home page of the figma link
### Checklist
- [x] App run correctly
- [x] The code has been tested in the local environment.
- [x] No convention errors

2023-08-08 16:38 UTC, st-trangnguyen requested changes
chị chưa có thời gian review kĩ bài này nhưng tổng thể em fix theo nhưng feedback dưới đây

- define variable cho color
- define grid layout (row-column) và apply vào
- em xây dựng css cho các module button, badge (cái tag giảm bao nhiều % giá), section header để có tính tái sử dụng cao
ví dụ: btn btn-primary, btn btn-secondary, btn btn-outline, badge badge-danger, section-header.section-header-center (cái nào có button show more thì section-header còn cái nào title cần vào giữa thì thêm class section-header-center zo)
tham khảo thêm bootstrap về cách xây dựng các utility, module... 

https://getbootstrap.com/docs/4.0/layout/overview/#containers
https://getbootstrap.com/docs/4.0/layout/grid/
https://getbootstrap.com/docs/4.0/layout/media-object/
https://getbootstrap.com/docs/4.0/utilities/flex/
https://getbootstrap.com/docs/4.0/utilities/text/
https://getbootstrap.com/docs/4.0/components/card/
https://getbootstrap.com/docs/4.0/components/buttons/
https://getbootstrap.com/docs/4.0/components/badge/
https://getbootstrap.com/docs/4.0/components/forms/
https://getbootstrap.com/docs/4.0/components/navs/

2023-08-08 16:38 UTC, st-trangnguyen commented on 1.html
> +          <a href="" class="navbar-item-link text-content">Men</a>
Rank B: em style lun cho class link, và làm thêm trang thái hover đổi màu cho nó, ko add thêm class

2023-08-08 23:57 UTC, st-ngabui requested changes

2023-08-08 23:57 UTC, st-ngabui commented on styles.css
> +  font-family: Arial, sans-serif;
E define font-family chưa đúng với design, check lại chỗ này.
Define font-family nơi thẻ body, và define thêm cho body những thuộc tính chung: font-size, line-height, color, font-weigh

2023-08-08 23:57 UTC, st-ngabui commented on styles.css
> +  flex-direction: row;
flex-direction mặc định là row rồi, ko cần khai báo thêm

2023-08-08 23:57 UTC, st-ngabui commented on styles.css
> +}
Những layout này ko cần thêm thuộc tính display: flex, nó sẽ dùng kết hợp cùng với .flex-row, .flex-col phía trên.
Tên class dài, có thể suy nghĩ cho nó ngắn bớt. Ví dụ:  justify-content-center -> f-center-x

2023-08-08 23:57 UTC, st-ngabui commented on styles.css
> +}
Đặt tên class vào cho header và CSS, header để fixed

2023-08-08 23:57 UTC, st-ngabui commented on styles.css
> +}
- Đặt tên class tránh CSS trực tiếp cho thẻ như này
- CSS của e đoạn này chưa đúng, e xem lại

2023-08-08 23:57 UTC, st-ngabui commented on styles.css
> +}
Đặt variable cho màu sắc
Tên class chưa hợp lý, vì CSS mỗi màu cho text nên đặt tên class là `txt-{color-name}`

2023-08-08 23:57 UTC, st-ngabui commented on styles.css
> +}
CSS chỗ này chưa hợp lý, e xem lại

2023-08-08 23:57 UTC, st-ngabui commented on styles.css
> +}
padding ko đi dùng % e nha. Chị thấy e sử dụng % rất nhiều chỗ, nên xem lại khi nào thì nên dùng %

2023-08-08 23:57 UTC, st-ngabui commented on styles.css
> +}
Không fix cứng width cho thẻ input như này

2023-08-09 00:06 UTC, st-ngabui commented on styles.css
> +  padding: 10px 0;
Em xem lại cách check design của em, chị thấy giá trị padding của e sai rất nhiều chỗ

2023-08-10 02:54 UTC, merged